In [1]:
import numpy as np

In [61]:
X = [
    [148, 24, 1385],
    [132, 25, 2031],
    [453, 11, 86],
    [158, 24, 105],
    [172, 25, 201],
    [413, 11, 86.0002222],
    [38,  54, 185],
    [142, 25, 431],
    [453, 31, 86.001],
]
X = np.array(X)
X.shape, X

((9, 3),
 array([[ 148.       ,   24.       , 1385.       ],
        [ 132.       ,   25.       , 2031.       ],
        [ 453.       ,   11.       ,   86.       ],
        [ 158.       ,   24.       ,  105.       ],
        [ 172.       ,   25.       ,  201.       ],
        [ 413.       ,   11.       ,   86.0002222],
        [  38.       ,   54.       ,  185.       ],
        [ 142.       ,   25.       ,  431.       ],
        [ 453.       ,   31.       ,   86.001    ]]))

In [62]:
ones = np.ones(X.shape[0])
X = np.column_stack([ones, X])
y = [10000, 20000, 15000, 20050, 10000, 20000, 15000, 25000, 12000]

In [63]:
XTX = X.T.dot(X)
XTX

array([[9.00000000e+00, 2.10900000e+03, 2.30000000e+02, 4.59600122e+03],
       [2.10900000e+03, 6.96471000e+05, 4.41150000e+04, 7.05900545e+05],
       [2.30000000e+02, 4.41150000e+04, 7.14600000e+03, 1.16883033e+05],
       [4.59600122e+03, 7.05900545e+05, 1.16883033e+05, 6.33678621e+06]])

In [64]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 3.21929032e+00, -5.25373550e-03, -6.09534437e-02,
        -6.25368122e-04],
       [-5.25373550e-03,  1.09319214e-05,  8.47794919e-05,
         1.02891925e-06],
       [-6.09534437e-02,  8.47794919e-05,  1.44603993e-03,
         8.09222164e-06],
       [-6.25368122e-04,  1.02891925e-06,  8.09222164e-06,
         3.47500216e-07]])

In [65]:
w_full = XTX.dot(X.T).dot(y)
w_full

array([4.21856929e+11, 7.73500750e+13, 1.04131388e+13, 5.06879493e+14])

In [66]:
w0 = w_full[0]
w = w_full[1:]
w0, w

(np.float64(421856929230.4791),
 array([7.73500750e+13, 1.04131388e+13, 5.06879493e+14]))

In [67]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [68]:
train_linear_regression(X, y)

(np.float64(3.4248876315982214e+20),
 array([-2.59706973e+20, -2.24049712e+02, -2.83214515e+03,  0.00000000e+00]))